#mac specfic overrides

#java
export JAVA_HOME=`/usr/libexec/java_home`

# Customize to your needs...
export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin/:/usr/bin/:~/bin/:/usr/local/lib64/:/Users/gtakahashi/projects/tesora/bin/unix:$PATH
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

test -e ~/.dircolors && eval `dircolors -b ~/.dircolors`
alias ls="ls --color=always" 
alias grep="grep --color=always"
alias egrep="egrep --color=always"
